version: 2

defaults: &defaults
  working_directory: ~/repo
  environment:
    LC_ALL: C.UTF-8

install_hex_rebar: &install_hex_rebar
  run:
    name: Install hex and rebar
    command: |
      mix local.hex --force
      mix local.rebar --force

install_system_deps: &install_system_deps
  run:
    name: Install system dependencies
    command: |
        apk add build-base libmnl-dev
        apk add fwup --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community

jobs:
  build_elixir_1_11_otp_23:
    docker:
      - image: hexpm/elixir:1.11.3-erlang-23.2.2-alpine-3.12.1
    <<: *defaults
    steps:
      - checkout
      - <<: *install_hex_rebar
      - <<: *install_system_deps
      - restore_cache:
          keys:
            - v1-mix-cache-{{ checksum "mix.lock" }}
      - run: mix deps.get
      - run: mix format --check-formatted
      - run: mix deps.unlock --check-unused
      # SUDO=true -> disable autodetection of a host build and the "helpful"
      # call to sudo
      - run: SUDO=true mix compile --warnings-as-errors
      - run: mix docs
      - run: mix hex.build
      - run: mix test
      - run: mix dialyzer
      - save_cache:
          key: v1-mix-cache-{{ checksum "mix.lock" }}
          paths:
            - _build
            - deps

  build_elixir_1_10_otp_23:
    docker:
      - image: hexpm/elixir:1.10.4-erlang-23.1.2-alpine-3.12.1
    <<: *defaults
    steps:
      - checkout
      - <<: *install_hex_rebar
      - <<: *install_system_deps
      - run: mix deps.get
      - run: SUDO=true mix compile
      - run: mix test

workflows:
  version: 2
  build_test:
    jobs:
      - build_elixir_1_11_otp_23
      - build_elixir_1_10_otp_23

